# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findMatchingSeedsCpp <- function(candidates, targetState, verbose = FALSE, progressEvery = 10000L) {
    .Call(`_opdisDownsampling_findMatchingSeedsCpp`, candidates, targetState, verbose, progressEvery)
}

findMatchingSeedsBatchCpp <- function(candidates, targetState, batchSize = 1000L, verbose = FALSE) {
    .Call(`_opdisDownsampling_findMatchingSeedsBatchCpp`, candidates, targetState, batchSize, verbose)
}

